"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%3b0n0!j7i&-i!x&k0bch%@-h^5-*quprey5xj+^_gcsb5&)ja'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 開発環境でもWhiteNoiseを使うため、staticfilesよりも上にINSTALLED_APPSをセット
    # http://whitenoise.evans.io/en/stable/django.html#using-whitenoise-in-development
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'myapp',
]

MIDDLEWARE = [
    # SecurityMiddlewareよりも上でWhiteNoiseのMiddlewareを読み込む
    # http://whitenoise.evans.io/en/stable/django.html#enable-whitenoise
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

# dj_database_urlによるDatabase設定
import dj_database_url
# Herokuには'ON_HEROKU'という環境変数がある前提
if 'ON_HEROKU' in os.environ:
    DATABASES = {
        'default': dj_database_url.config()
    }
else:
    # 以前と異なり、engineはいらないらしい
    # (以前)https://github.com/thinkAmi/dj_ringo_tabetter/blob/70b000cc8b583f2be58606fe4f1d0707e1ce7324/dj_ringo_tabetter/settings.py#L111
    DATABASES = {
        'default':
            dj_database_url.config(
                default='postgres://postgres:postgres@127.0.0.1:5432/try_heroku_django_uwsgi',
            )
    }



# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# Herokuへpush時に自動的で走るcollectstaticに対応するため、STATIC_ROOTを設定
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Herokuで動かすために、接続可能なホストを設定
# 開発的なものなので、全ホストをOKにしておく
# http://stackoverflow.com/questions/31685688/is-allowed-hosts-needed-on-heroku
ALLOWED_HOSTS = ['*']
